spring:
  datasource:
    url: jdbc:postgresql://localhost/circle_test
    username: circle_test

clouds:
  aws:
    s3:
      endpoint-url:   ""
      region:         ""
      access-key:     ""
      secret-key:     ""
      bucket-name:    ""
