spring:
  datasource:
    url: jdbc:postgresql://localhost/blog
    username: blog
    password: p@ssw0rd
  thymeleaf.cache: false

clouds:
  aws:
    s3:
      endpoint-url:   ""
      region:         ""
      access-key:     ""
      secret-key:     ""
      bucket-name:    ""
